---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  labels:
    app: flask-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      securityContext:
        runAsUser: 999
      containers:
      - name: flask-app
        image: harbor.ischool.syr.edu/examples/flask-mysql-example:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "128Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
        env:
        - name: APP_NAME
          value: "Guest Book"
        - name: APP_SECRET  
          valueFrom:
            secretKeyRef:
              name: flask-app-secret
              key: secret
        - name: DB_HOST
          value: mariadb
        - name: DB_NAME
          value: logbook
        - name: DB_USER
          value: root
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: mariadb-root-password
              key: password 
      - name: tls-sidecar
        image: nginxinc/nginx-unprivileged:latest
        resources:
          requests:
            memory: "128Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
          - name: https
            containerPort: 8443
            protocol: TCP
        volumeMounts:
          - name: sidecar-config
            mountPath: "/etc/nginx"
            readOnly: true
          - name: sidecar-certs
            mountPath: "/certs"
            readOnly: true
      dnsPolicy: "ClusterFirst"
      dnsConfig:
        nameservers:
          - 10.96.0.10
          - 128.230.108.24
          - 128.230.108.27
      volumes:
        - name: sidecar-config
          configMap:
            name: nginx-configmap
        - name: sidecar-certs
          secret:
            secretName: tls-certs
      imagePullSecrets:
      - name: regcred