apiVersion: v1
kind: Service
metadata:
  labels:
    app: mariadb
  name: mariadb-nodeport
spec:
  ports:
  - port: 3306
    nodePort: 31081
    protocol: TCP
    targetPort: 3306
  selector:
    app: mariadb
  type: NodePort