---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
data:
  nginx.conf: |
    user nginx;
    worker_processes auto;
    events {
      worker_connections 1024;
    }
    # 
    #pid        /var/run/nginx.pid;
    pid         /tmp/nginx.pid;

    http {
        server {
            listen [::]:8443 ssl;
            listen 8443 ssl;

            server_name localhost;
            ssl_session_cache    shared:SSL:10m; # a 1mb cache can hold about 4000 sessions, so we can hold 40000 sessions
            ssl_session_timeout  24h;

            keepalive_timeout 300; # up from 75 secs default

            ssl_certificate      /certs/tls.crt;
            ssl_certificate_key  /certs/tls.key;

            location / {
                proxy_pass http://localhost:5000;

                proxy_set_header Connection "";
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $remote_addr;
            }
        }
    }